<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <title><?php echo Mage::getStoreConfig('turnto_admin/mobileconfig/title'); ?></title>
    <meta name="viewport" content="width=device-width,  initial-scale=1.0, maximum-scale=1.0,  user-scalable=0"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>

    <?php $helper = Mage::helper('turnto_mobile_helper/data'); ?>

    <script type="text/javascript">
        var turnToConfig = {
            siteKey: "<?php echo Mage::getStoreConfig('turnto_admin/general/site_key'); ?>",
            host: "<?php echo $helper->getHostWithoutProtocol(); ?>",
            staticHost: "<?php echo $helper->getStaticHostWithoutProtocol(); ?>",
            imageStoreBase:'<?php echo Mage::getStoreConfig('turnto_admin/general/image_store_base'); ?>',
            setupType: "mobileTT"
        };
    </script>
    <script type="text/javascript" src="<?php echo Mage::getStoreConfig('turnto_admin/general/url')?>/tra4_2/mobile-landing.js"></script>
    <link rel="stylesheet" href="<?php echo Mage::getStoreConfig('turnto_admin/general/static_url')?>/tra4_2/tra.css" type="text/css"/>
</head>

<body>
<div id="mobileTT-content"></div>
</body>
</html>