<?php


?>
   <div style="margin-left:215px;">
<!--      --><?php //if($this->isFeedActivated()): ?>
<!--       <p style="margin-bottom:0; color:green;"><b>--><?php //echo $this->__('Feed is activated!') ?><!--</b></p>-->
<!--      --><?php //else: ?>
<!--        <p style="margin-bottom:0; color:red;"><b>--><?php //echo $this->__('Unable to access the feed! Please make sure your Turnto account is activated and configrations are correctly set.') ?><!--</b></p>-->

<!--      --><?php //endif; ?>
    </div>
